import { Inter } from "next/font/google"
import "./globals.css";
import Navbar from "./components/Navbar";
import { Toaster } from "react-hot-toast";

const interFont = Inter({
  weight:["100","300","400","700","900"],
  subsets:["latin"],
  display:'swap'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${interFont.className} antialiased mb-[90px]`}
      >
        <div className="h-full bg-gray-100 m-auto min-w-[160px] max-w-[540px]">
          <Toaster/>
          {children}
        </div>
        <Navbar/>
      </body>
    </html>
  );
}
